### ISSUE TITLE
Question about the method used for constructing the intermediate knowledge graph layer in MedGraphRAG

### ISSUE THREAD

**Issue by yanyanhuang** [MedicineToken/Medical-Graph-RAG#11]
Hi,

Thank you for your impressive work on the Medical Graph RAG. I have a question regarding the construction of the intermediate knowledge graph layer, where you mentioned using **4.8 million medical papers and 30,000 textbooks**.

Could you please share more details on the method you used for building this knowledge graph? Specifically: Did you use GPT or an open-source LLM to generate and organize the connections in the graph? Or, did you employ another, possibly simpler, graph construction method?

I’m interested in understanding this because, if LLMs were heavily involved in the construction, there would likely be significant computational costs associated with this approach.

Thank you for your time and for any insights you can share!

**Comment by WuJunde** [comment]
I did deduplication on the doc, then used llama

**Comment by yanyanhuang** [comment]
Thank you very much for your reply!
