### ISSUE TITLE
Failed to setup the conda environment

### ISSUE THREAD

**Issue by b224618** [MedicineToken/Medical-Graph-RAG#7]
Dear authors,

Thank you for sharing the code. But When I run the command 'conda env create -f medgraphrag.yml', I got the following error: 

$ conda env create -f medgraphrag.yml
Channels:
 - pytorch
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - pytorch
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested zlib ==1.2.13 h53f4e23_5
  - nothing provides requested zeromq ==4.3.5 hebf3989_1
  - nothing provides requested xz ==5.4.6 h80987f9_0
  - nothing provides requested wheel ==0.41.2 py310hca03da5_0
  - nothing provides requested typing_extensions ==4.9.0 py310hca03da5_1
  - nothing provides requested tk ==8.6.12 hb8d0fd4_0
  - nothing provides requested sqlite ==3.41.2 h80987f9_0
  - nothing provides requested readline ==8.2 h1a28f6b_0
  - nothing provides requested python ==3.10.9 h3ba56d0_0_cpython
  - nothing provides requested psutil ==5.9.8 py310hd125d64_0
  - nothing provides requested pip ==23.3.1 py310hca03da5_0
  - nothing provides requested openssl ==3.2.1 h0d3ecfb_1
  - nothing provides requested openblas-devel ==0.3.21 hca03da5_0
  - nothing provides requested openblas ==0.3.21 hca03da5_0
  - nothing provides requested ncurses ==6.4 h313beb8_0
  - nothing provides requested llvm-openmp ==18.1.2 hcd81f8e_0
  - nothing provides requested libzlib ==1.2.13 h53f4e23_5
  - nothing provides requested libsqlite ==3.45.2 h091b4b1_0
  - nothing provides requested libsodium ==1.0.18 h27ca646_1
  - nothing provides requested libopenblas ==0.3.21 h269037a_0
  - nothing provides requested libgfortran5 ==11.3.0 h009349e_28
  - nothing provides requested libgfortran ==5.0.0 11_3_0_hca03da5_28
  - nothing provides requested libffi ==3.4.4 hca03da5_0
  - nothing provides requested libfaiss ==1.8.0 hcb8d3e5_0_cpu
  - nothing provides requested libcxx ==16.0.6 h4653b0c_0
  - nothing provides requested jupyter_core ==5.7.2 py310hbe9552e_0
  - nothing provides __osx needed by ipykernel-6.29.3-pyh3cd1d5f_0
  - nothing provides requested faiss-cpu ==1.8.0 py3.10_hbe593ad_0_cpu
  - nothing provides requested debugpy ==1.8.1 py310h692a8b6_0
  - nothing provides requested ca-certificates ==2024.3.11 hca03da5_0
  - nothing provides requested bzip2 ==1.0.8 h80987f9_5
  - nothing provides requested annotated-types ==0.6.0 py310hca03da5_0

Could not solve for environment specs
The following packages are incompatible
├─ annotated-types ==0.6.0 py310hca03da5_0 does not exist (perhaps a typo or a missing channel);
├─ bzip2 ==1.0.8 h80987f9_5 does not exist (perhaps a typo or a missing channel);
├─ ca-certificates ==2024.3.11 hca03da5_0 does not exist (perhaps a typo or a missing channel);
├─ debugpy ==1.8.1 py310h692a8b6_0 does not exist (perhaps a typo or a missing channel);
├─ faiss-cpu ==1.8.0 py3.10_hbe593ad_0_cpu does not exist (perhaps a typo or a missing channel);
├─ ipykernel ==6.29.3 pyh3cd1d5f_0 is not installable because it requires
│  └─ __osx, which is missing on the system;
├─ jupyter_core ==5.7.2 py310hbe9552e_0 does not exist (perhaps a typo or a missing channel);
├─ libcxx ==16.0.6 h4653b0c_0 does not exist (perhaps a typo or a missing channel);
├─ libfaiss ==1.8.0 hcb8d3e5_0_cpu does not exist (perhaps a typo or a missing channel);
├─ libffi ==3.4.4 hca03da5_0 does not exist (perhaps a typo or a missing channel);
├─ libgfortran5 ==11.3.0 h009349e_28 does not exist (perhaps a typo or a missing channel);
├─ libgfortran ==5.0.0 11_3_0_hca03da5_28 does not exist (perhaps a typo or a missing channel);
├─ libopenblas ==0.3.21 h269037a_0 does not exist (perhaps a typo or a missing channel);
├─ libsodium ==1.0.18 h27ca646_1 does not exist (perhaps a typo or a missing channel);
├─ libsqlite ==3.45.2 h091b4b1_0 does not exist (perhaps a typo or a missing channel);
├─ libzlib ==1.2.13 h53f4e23_5 does not exist (perhaps a typo or a missing channel);
├─ llvm-openmp ==18.1.2 hcd81f8e_0 does not exist (perhaps a typo or a missing channel);
├─ ncurses ==6.4 h313beb8_0 does not exist (perhaps a typo or a missing channel);
├─ openblas-devel ==0.3.21 hca03da5_0 does not exist (perhaps a typo or a missing channel);
├─ openblas ==0.3.21 hca03da5_0 does not exist (perhaps a typo or a missing channel);
├─ openssl ==3.2.1 h0d3ecfb_1 does not exist (perhaps a typo or a missing channel);
├─ pip ==23.3.1 py310hca03da5_0 does not exist (perhaps a typo or a missing channel);
├─ psutil ==5.9.8 py310hd125d64_0 does not exist (perhaps a typo or a missing channel);
├─ python ==3.10.9 h3ba56d0_0_cpython does not exist (perhaps a typo or a missing channel);
├─ readline ==8.2 h1a28f6b_0 does not exist (perhaps a typo or a missing channel);
├─ sqlite ==3.41.2 h80987f9_0 does not exist (perhaps a typo or a missing channel);
├─ tk ==8.6.12 hb8d0fd4_0 does not exist (perhaps a typo or a missing channel);
├─ typing_extensions ==4.9.0 py310hca03da5_1 does not exist (perhaps a typo or a missing channel);
├─ wheel ==0.41.2 py310hca03da5_0 does not exist (perhaps a typo or a missing channel);
├─ xz ==5.4.6 h80987f9_0 does not exist (perhaps a typo or a missing channel);
├─ zeromq ==4.3.5 hebf3989_1 does not exist (perhaps a typo or a missing channel);
└─ zlib ==1.2.13 h53f4e23_5 does not exist (perhaps a typo or a missing channel).

I'm using Linux system and the cuda version is 12.4
I also tried removing the version and build names, but all failed. Do you have any suggestion on setting up the environments?

Thank you in advance!

**Comment by JohannHalley** [comment]
same issue for me, ` conda env create -f medgraphrag.yml` doesn't work.

**Comment by billbradley** [comment]
Same issue for me.

**Comment by guojunxi** [comment]
Same issue for me.

**Comment by LyxDLiI** [comment]
Same issue for me.

**Comment by ReMuSoMeGA93** [comment]
It does not work but I re-created this algorithm step-wise from the source code. My advice - don't waste your time. This code 100% does not even remotely reflect the innovative "U-Method" claimed in the arxiv paper. Not even close. I have no idea what this code is supposed to be.

**Comment by FarhanMubashir** [comment]
Hi,
I'm currently trying to set up the project and am encountering the same issue as described in Issue #7 regarding the failed Conda environment setup. Despite following the setup instructions provided, I still receive the same error.

**Comment by WuJunde** [comment]
I have updated .yml file, it is supposed to work now.

**Comment by 1-2-77** [comment]
Hello, I'm facing similar issues when creating the env:

conda env create -f medgraphrag.yml 


`Using cached zipp-3.18.1-py3-none-any.whl (8.2 kB)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py): started
  Building wheel for googlemaps (setup.py): finished with status 'error'
  Running setup.py clean for googlemaps
Failed to build googlemaps

Pip subprocess error:
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /opt/anaconda3/envs/medgraphrag/lib/python3.10/site-packages/setuptools/__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
`

**Comment by WuJunde** [comment]
> Hello, I'm facing similar issues when creating the env:
> 
> conda env create -f medgraphrag.yml
> 
> ```
> Using cached zipp-3.18.1-py3-none-any.whl (8.2 kB)
> Building wheels for collected packages: googlemaps
>   Building wheel for googlemaps (setup.py): started
>   Building wheel for googlemaps (setup.py): finished with status 'error'
>   Running setup.py clean for googlemaps
> Failed to build googlemaps
> 
> Pip subprocess error:
>   error: subprocess-exited-with-error
>   
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [42 lines of output]
>       /opt/anaconda3/envs/medgraphrag/lib/python3.10/site-packages/setuptools/__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
>       !!
>       
>               ********************************************************************************
>               Requirements should be satisfied by a PEP 517 installer.
>               If you are using pip, you can try `pip install --use-pep517`.
>               ********************************************************************************
> ```

download docker image if you really cannot solve it: https://hub.docker.com/layers/jundewu/medgraphrag/latest/images/sha256:a5c7a2073370bfc27cef8a0f67f104c8fc8a9cc4f1b4f14423cead4f7315ad1b?uuid=96578819-fb91-493a-925f-a8388a5ed69c%0A
